name: miscelanius
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_riverpod: ^2.3.6
  flutter_share: ^2.0.0
  geolocator: ^9.0.2
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  local_auth: ^2.1.6
  local_auth_android: ^1.0.32
  permission_handler: ^10.4.3
  sensors_plus: ^3.0.3
  wakelock_plus: ^1.1.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
